name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      # Install
      - name: Install Dependencies
        run: npm ci --loglevel=error

      # Build
      - name: Build Package
        run: npm run build:prod

      # Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'dist'
          path: './dist'
