name: Pull requests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      # Install
      - name: Install Dependencies
        run: npm ci --loglevel=error

      # Tests
      - name: Unit tests
        run: npm run test:cov

      # - name: Codecov
      #   uses: codecov/codecov-action@v1.2.2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage/lcov.info
      #     fail_ci_if_error: true

      # Build
      - name: Build Package
        run: npm run build:prod
